'use strict';

const TAG = 'link-core:client';

const DEFAULT_RECONNECT_GROWTH        = 1.5;
const DEFAULT_RECONNECT_INITIAL_MS    = 1_000;
const DEFAULT_RPC_TIMEOUT_MS          = 5_000;
const DEFAULT_HELLO_ACK_DIAGNOSTIC_MS = 5_000;
const DEFAULT_MAX_RECENT_IDS          = 10_000;
const DEFAULT_RECONNECT_MAX_MS        = 10_000;
const DEFAULT_STATUS_INTERVAL_MS      = 10_000;
const DEFAULT_MAX_MESSAGE_BYTES       = 1_048_576;
const DEFAULT_REPLAY_WINDOW_MS        = 5 * 60_000;
const DEFAULT_MAX_BUFFERED_BYTES      = 4 * 1_048_576; // 4 MiB

module.exports = {
  TAG,
  DEFAULT_RPC_TIMEOUT_MS,
  DEFAULT_MAX_RECENT_IDS,
  DEFAULT_RECONNECT_GROWTH,
  DEFAULT_RECONNECT_MAX_MS,
  DEFAULT_REPLAY_WINDOW_MS,
  DEFAULT_MAX_MESSAGE_BYTES,
  DEFAULT_STATUS_INTERVAL_MS,
  DEFAULT_MAX_BUFFERED_BYTES,
  DEFAULT_RECONNECT_INITIAL_MS,
  DEFAULT_HELLO_ACK_DIAGNOSTIC_MS,
};
