'use strict';

const TAG = 'link-core:client';

const DEFAULT_DRAIN_RETRY_MS          = 25;
const DEFAULT_MAX_LISTENERS           = 100;
const DEFAULT_MAX_CONCURRENT_RPC      = 256;
const DEFAULT_RECONNECT_GROWTH        = 1.5;
const DEFAULT_RECONNECT_JITTER        = 0.5;
const DEFAULT_RECONNECT_INITIAL_MS    = 1_000;
const DEFAULT_RPC_TIMEOUT_MS          = 5_000;
const DEFAULT_HELLO_ACK_DIAGNOSTIC_MS = 5_000;
const DEFAULT_STOP_DRAIN_MS           = 5_000;
const DEFAULT_MAX_RECENT_IDS          = 10_000;
const DEFAULT_RECONNECT_MAX_MS        = 10_000;
const DEFAULT_STATUS_INTERVAL_MS      = 10_000;
const DEFAULT_KEEPALIVE_INTERVAL_MS   = 30_000;
const DEFAULT_MAX_RECONNECT_ATTEMPTS  = Infinity;
const DEFAULT_MAX_MESSAGE_BYTES       = 1_048_576;
const DEFAULT_REPLAY_WINDOW_MS        = 5  * 60_000;
const DEFAULT_MAX_BUFFERED_BYTES      = 4  * 1_048_576;
const DEFAULT_MAX_OUTBOX_BYTES        = 16 * 1_048_576;

module.exports = {
  TAG,
  DEFAULT_STOP_DRAIN_MS,
  DEFAULT_MAX_LISTENERS,
  DEFAULT_RPC_TIMEOUT_MS,
  DEFAULT_MAX_RECENT_IDS,
  DEFAULT_DRAIN_RETRY_MS,
  DEFAULT_RECONNECT_GROWTH,
  DEFAULT_RECONNECT_JITTER,
  DEFAULT_RECONNECT_MAX_MS,
  DEFAULT_REPLAY_WINDOW_MS,
  DEFAULT_MAX_OUTBOX_BYTES,
  DEFAULT_MAX_MESSAGE_BYTES,
  DEFAULT_MAX_CONCURRENT_RPC,
  DEFAULT_STATUS_INTERVAL_MS,
  DEFAULT_MAX_BUFFERED_BYTES,
  DEFAULT_RECONNECT_INITIAL_MS,
  DEFAULT_KEEPALIVE_INTERVAL_MS,
  DEFAULT_MAX_RECONNECT_ATTEMPTS,
  DEFAULT_HELLO_ACK_DIAGNOSTIC_MS
};